name: Update Version

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  update-version:
    name: Update Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name: Setup Git
        run: |
          git config http.sslVerify false
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
      - name: Update version.go
        run: |
          VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          sed -i "s/const VERSION = \".*\"/const VERSION = \"$VERSION\"/" cmd/version.go
          
      - name: Commit changes and update tag
        run: |
          git add .
          git commit -m "chore: update version to ${{ github.ref_name }}"
          git tag -d ${{ github.ref_name }}
          git push origin :refs/tags/${{ github.ref_name }}
          git tag ${{ github.ref_name }}
          git push origin HEAD:${{ github.event.repository.default_branch }} --tags --force