name: Update Version

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  update-version:
    name: Update Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name: Setup Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
      - name: Update version.go
        run: |
          set -e
          if [ ! -f "cmd/version.go" ]; then
            echo "Error: cmd/version.go file not found"
            exit 1
          fi
          VERSION=$(echo ${{ github.ref_name }} | sed 's/^v//')
          sed -i "s/const VERSION = \".*\"/const VERSION = \"$VERSION\"/" cmd/version.go
          
      - name: Commit changes and update tag
        run: |
          set -e
          REPO="https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          
          # Check if there are changes to commit
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add .
            git commit -m "chore: update version to ${{ github.ref_name }}"
          fi
          
          # Update tag
          git tag --delete ${{ github.ref_name }} || true
          git push ${REPO} --delete :refs/tags/${{ github.ref_name }} || true
          git tag ${{ github.ref_name }}
          git push ${REPO} HEAD:${{ github.event.repository.default_branch }} --tags --force