name: Update Version

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  update-version:
    name: Update Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          
      - name: Update version.go
        run: |
          VERSION=v0.2.10
          sed -i "s/const VERSION = \".*\"/const VERSION = \"$VERSION\"/" cmd/version.go
          
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
